---
logging:
  level: INFO
  loggers:
    com.baku: DEBUG

country: ${COUNTRY_NAME:-India}

server:
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

quartzJobConfig:
  threadPoolSize: 2
