---
logging:
  level: INFO
  loggers:
    com.baku: DEBUG

country: ${COUNTRY_NAME}

server:
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8081
